//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriadPad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriadPad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap COMPILE {
            get {
                object obj = ResourceManager.GetObject("COMPILE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to design D
        ///def
        ///enddes.
        /// </summary>
        internal static string DesignInitialCode {
            get {
                return ResourceManager.GetString("DesignInitialCode", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon FILLCIRC {
            get {
                object obj = ResourceManager.GetObject("FILLCIRC", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon FILPAPER {
            get {
                object obj = ResourceManager.GetObject("FILPAPER", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icondition IC
        ///endic.
        /// </summary>
        internal static string IConditionInitialCode {
            get {
                return ResourceManager.GetString("IConditionInitialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iprocedure IP
        ///endip.
        /// </summary>
        internal static string IProcedureInitialCode {
            get {
                return ResourceManager.GetString("IProcedureInitialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model M
        ///def
        ///endmod.
        /// </summary>
        internal static string ModelInitialCode {
            get {
                return ResourceManager.GetString("ModelInitialCode", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon OPENFILE {
            get {
                object obj = ResourceManager.GetObject("OPENFILE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to routine R
        ///endrout.
        /// </summary>
        internal static string RoutineInitialCode {
            get {
                return ResourceManager.GetString("RoutineInitialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to structure S
        ///def
        ///endstr.
        /// </summary>
        internal static string StructureInitialCode {
            get {
                return ResourceManager.GetString("StructureInitialCode", resourceCulture);
            }
        }
    }
}
